sudo: required
services:
  - docker

before_install:
  - docker build -t dimapaschenko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dimapaschenko/react-test npm test -- --coverage

after_success:
  - docker build -t dimapaschenko/multi-client ./client
  - docker build -t dimapaschenko/multi-nginx ./nginx
  - docker build -t dimapaschenko/multi-server ./server
  - docker build -t dimapaschenko/multi-worker ./worker
  # ADD next Variables to Travic as Environment Variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dimapaschenko/multi-client
  - docker push dimapaschenko/multi-nginx
  - docker push dimapaschenko/multi-server
  - docker push dimapaschenko/multi-worker

